#! /bin/bash

if [[ $# < 2 ]]; then
    echo
    echo "usage: ./generate-plan <domain> <problem>"
    echo
    exit 1
fi


./prp $1 $2 --dump-policy 2 --final-fsap-free-round 1

python ~/Projects/prp/prp-scripts/translate_policy.py > human_policy.out

python ~/Projects/prp/prp-scripts/validator.py $1 $2 human_policy.out prp

dot -Tpng graph.dot > graph.png
